# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import encoder_pb2 as encoder__pb2


class EncoderStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.encode = channel.unary_unary(
        '/Encoder/encode',
        request_serializer=encoder__pb2.EncodeRequest.SerializeToString,
        response_deserializer=encoder__pb2.EncodeResponse.FromString,
        )
    self.decode = channel.unary_unary(
        '/Encoder/decode',
        request_serializer=encoder__pb2.DecodeRequest.SerializeToString,
        response_deserializer=encoder__pb2.DecodeResponse.FromString,
        )


class EncoderServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def encode(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def decode(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EncoderServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'encode': grpc.unary_unary_rpc_method_handler(
          servicer.encode,
          request_deserializer=encoder__pb2.EncodeRequest.FromString,
          response_serializer=encoder__pb2.EncodeResponse.SerializeToString,
      ),
      'decode': grpc.unary_unary_rpc_method_handler(
          servicer.decode,
          request_deserializer=encoder__pb2.DecodeRequest.FromString,
          response_serializer=encoder__pb2.DecodeResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Encoder', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
